version: '3.7'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"


  mysql_db:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db
    ports:
      - "8080:80"


