version: '3.7'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"


  mysql_db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: login
    volumes:
      - my-sqldb:/var/lib/mysql
    ports: 
     - '3306:3306'



  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      -"8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root


